### ISSUE TITLE
fset not loading

### ISSUE THREAD

**Issue by atgreen** [djha-skin/nrdl#1]
As I understand this line...

https://github.com/djha-skin/nrdl/blob/28487696c985647ebca1d967d3bcacfd4b69b6cf/cl/main.lisp#L7

...fset won't load, and the code that follows fails to build

**Comment by djha-skin** [comment]
Thank you,  yes,  master is unstable. I'll fix. In the mean time,  please check our the 0.3.0 tag. I'll probably be reverting to that anyway :)

**Comment by atgreen** [comment]
There is no such tag in github.  ocicl is just pulling from main right now, but if you make a 0.3.0 release, I'll pull from there instead.

**Comment by djha-skin** [comment]
Fixed:

* I cleaned up main so that it doesn't pull in FSet and all the tests pass.
* I Updated the README, adding documentation and sections for contributing and usage.
* I tagged (released) the current commit on MAIN as the tag `0.5.0`.

Thanks for using my library. Join the [Matrix channel (`nrdl:matrix.org`)](https://matrix.to/#/!mEdAmGzxTrQPWAYdfx:matrix.org?via=matrix.org), I'm happy to chat anytime :)
